"""
cuet_translate_fix.py
=====================
Fixes CUET subject translations by using a massive Indian GK + General English dictionary.
Covers: History, Polity, Geography, Economics, Current Affairs, English Grammar, Reasoning, Maths
"""
import sqlite3, re, sys, os, time
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from question_bank_db import _bank_conn, _bank_lock

# ══════════════════════════════════════════════════════════════════════════════
# MASSIVE CUET DICTIONARIES — 2000+ terms per language for Indian GK context
# ══════════════════════════════════════════════════════════════════════════════

CUET_PHRASES = {

# ════════════════════════════════════════════════════════════
# HINDI
# ════════════════════════════════════════════════════════════
"hi": {
    # ── Q-framing ──
    "Which of the following is NOT correct": "निम्न में से कौन सा सही नहीं है",
    "Which of the following is correct": "निम्न में से कौन सा सही है",
    "Which of the following": "निम्न में से कौन",
    "Which was the first": "पहला कौन सा था",
    "Which is the largest": "सबसे बड़ा कौन सा है",
    "Which is the smallest": "सबसे छोटा कौन सा है",
    "Which is the longest": "सबसे लंबा कौन सा है",
    "Which is the highest": "सबसे ऊँचा कौन सा है",
    "Which article of the Indian Constitution": "भारतीय संविधान का कौन सा अनुच्छेद",
    "None of the above": "उपर्युक्त में से कोई नहीं",
    "All of the above": "उपर्युक्त सभी",
    "Both A and B": "A और B दोनों",
    "Neither A nor B": "न A न B",
    "What is the capital of": "की राजधानी क्या है",
    "What is the currency of": "की मुद्रा क्या है",
    "What is the full form of": "का पूर्ण रूप क्या है",
    "Who is known as": "किसे कहा जाता है",
    "Who was the first": "पहले कौन थे",
    "Who was the founder of": "के संस्थापक कौन थे",
    "Who wrote the book": "पुस्तक किसने लिखी",
    "When did India get independence": "भारत को स्वतंत्रता कब मिली",
    "In which year": "किस वर्ष में",
    "In which state": "किस राज्य में",
    "How many members": "कितने सदस्य",
    "How many states": "कितने राज्य",
    "What is": "क्या है",
    "Who is": "कौन है",
    "Where is": "कहाँ है",
    "When was": "कब था",
    "Which year": "कौन से वर्ष",
    "How many": "कितने",
    "Find the": "ज्ञात कीजिए",
    "Calculate": "गणना कीजिए",
    "Simplify": "सरल कीजिए",
    "The correct answer is": "सही उत्तर है",
    "The correct option is": "सही विकल्प है",
    "Choose the correct": "सही चुनिए",
    "Select the correct": "सही चुनिए",
    "Identify the": "पहचानिए",
    "Match the following": "सुमेलित कीजिए",
    "Arrange in order": "क्रम में लगाइए",
    "is related to": "से संबंधित है",
    "is associated with": "से जुड़ा है",
    "is also called": "को यह भी कहते हैं",
    "is known as the": "के नाम से जाना जाता है",
    "is called the Father of": "को जनक कहा जाता है",
    "is the author of": "के लेखक हैं",
    "was established in": "में स्थापित किया गया",
    "was founded in": "में स्थापित किया गया",
    "came into effect": "लागू हुआ",
    "came into force": "लागू हुआ",
    "was enacted in": "में अधिनियमित किया गया",
    "is located in": "में स्थित है",
    "is situated in": "में स्थित है",
    "is bordered by": "की सीमा लगती है",
    "has a population of": "की जनसंख्या है",
    "has an area of": "का क्षेत्रफल है",
    # ── Indian Polity ──
    "Indian Constitution": "भारतीय संविधान",
    "Constitution of India": "भारत का संविधान",
    "Constituent Assembly": "संविधान सभा",
    "Fundamental Rights": "मूल अधिकार",
    "Fundamental Duties": "मूल कर्तव्य",
    "Directive Principles": "नीति निर्देशक तत्व",
    "Right to Equality": "समानता का अधिकार",
    "Right to Freedom": "स्वतंत्रता का अधिकार",
    "Right against Exploitation": "शोषण के विरुद्ध अधिकार",
    "Right to Education": "शिक्षा का अधिकार",
    "Right to Information": "सूचना का अधिकार",
    "Right to Constitutional Remedies": "संवैधानिक उपचारों का अधिकार",
    "Preamble of the Constitution": "संविधान की प्रस्तावना",
    "President of India": "भारत के राष्ट्रपति",
    "Vice President of India": "भारत के उपराष्ट्रपति",
    "Prime Minister of India": "भारत के प्रधानमंत्री",
    "Chief Minister": "मुख्यमंत्री",
    "Governor": "राज्यपाल",
    "Parliament of India": "भारत की संसद",
    "Lok Sabha": "लोक सभा",
    "Rajya Sabha": "राज्य सभा",
    "Supreme Court": "सर्वोच्च न्यायालय",
    "High Court": "उच्च न्यायालय",
    "Chief Justice of India": "भारत के मुख्य न्यायाधीश",
    "Attorney General": "महान्यायवादी",
    "Election Commission": "चुनाव आयोग",
    "Finance Commission": "वित्त आयोग",
    "Planning Commission": "योजना आयोग",
    "NITI Aayog": "नीति आयोग",
    "Comptroller and Auditor General": "नियंत्रक और महालेखापरीक्षक",
    "Union Public Service Commission": "संघ लोक सेवा आयोग",
    "State Public Service Commission": "राज्य लोक सेवा आयोग",
    "Panchayati Raj": "पंचायती राज",
    "73rd Amendment": "73वाँ संशोधन",
    "74th Amendment": "74वाँ संशोधन",
    "42nd Amendment": "42वाँ संशोधन",
    "Emergency provisions": "आपातकाल प्रावधान",
    "National Emergency": "राष्ट्रीय आपातकाल",
    "Article 370": "अनुच्छेद 370",
    "Article 356": "अनुच्छेद 356",
    "Article 32": "अनुच्छेद 32",
    "Article 21": "अनुच्छेद 21",
    "Article 19": "अनुच्छेद 19",
    "Article 14": "अनुच्छेद 14",
    "Article": "अनुच्छेद",
    "Schedule": "अनुसूची",
    "amendment": "संशोधन",
    "Amendment": "संशोधन",
    # ── Indian History ──
    "Indus Valley Civilization": "सिंधु घाटी सभ्यता",
    "Harappan Civilization": "हड़प्पा सभ्यता",
    "Vedic period": "वैदिक काल",
    "Maurya Empire": "मौर्य साम्राज्य",
    "Gupta Empire": "गुप्त साम्राज्य",
    "Mughal Empire": "मुगल साम्राज्य",
    "Delhi Sultanate": "दिल्ली सल्तनत",
    "British East India Company": "ब्रिटिश ईस्ट इंडिया कंपनी",
    "Indian National Congress": "भारतीय राष्ट्रीय कांग्रेस",
    "Non-Cooperation Movement": "असहयोग आंदोलन",
    "Quit India Movement": "भारत छोड़ो आंदोलन",
    "Civil Disobedience Movement": "सविनय अवज्ञा आंदोलन",
    "Swadeshi Movement": "स्वदेशी आंदोलन",
    "Salt March": "नमक मार्च (दांडी मार्च)",
    "Dandi March": "दांडी मार्च",
    "Partition of Bengal": "बंगाल विभाजन",
    "Partition of India": "भारत का विभाजन",
    "Independence of India": "भारत की स्वतंत्रता",
    "Indian Rebellion of 1857": "1857 का भारतीय विद्रोह",
    "Battle of Plassey": "प्लासी का युद्ध",
    "Battle of Panipat": "पानीपत का युद्ध",
    "Chandragupta Maurya": "चंद्रगुप्त मौर्य",
    "Ashoka the Great": "महान अशोक",
    "Akbar the Great": "महान अकबर",
    "Mahatma Gandhi": "महात्मा गांधी",
    "Jawaharlal Nehru": "जवाहरलाल नेहरू",
    "Subhas Chandra Bose": "सुभाष चंद्र बोस",
    "Bhimrao Ramji Ambedkar": "भीमराव रामजी अंबेडकर",
    "B.R. Ambedkar": "बी.आर. अंबेडकर",
    "Sardar Vallabhbhai Patel": "सरदार वल्लभभाई पटेल",
    "Rabindranath Tagore": "रबीन्द्रनाथ टैगोर",
    "Swami Vivekananda": "स्वामी विवेकानंद",
    "flourished around": "लगभग इस काल में फला-फूला",
    "founded by": "द्वारा स्थापित",
    "ruled by": "द्वारा शासित",
    # ── Indian Geography ──
    "Largest state of India by area": "क्षेत्रफल के अनुसार भारत का सबसे बड़ा राज्य",
    "Smallest state of India": "भारत का सबसे छोटा राज्य",
    "Longest river of India": "भारत की सबसे लंबी नदी",
    "Highest peak in India": "भारत की सबसे ऊँची चोटी",
    "River Ganga": "गंगा नदी",
    "River Yamuna": "यमुना नदी",
    "River Brahmaputra": "ब्रह्मपुत्र नदी",
    "River Godavari": "गोदावरी नदी",
    "River Krishna": "कृष्णा नदी",
    "Western Ghats": "पश्चिमी घाट",
    "Eastern Ghats": "पूर्वी घाट",
    "Himalayan range": "हिमालय पर्वत श्रृंखला",
    "Thar Desert": "थार मरुस्थल",
    "Deccan Plateau": "दक्कन पठार",
    "Indian Ocean": "हिंद महासागर",
    "Bay of Bengal": "बंगाल की खाड़ी",
    "Arabian Sea": "अरब सागर",
    "Tropic of Cancer": "कर्क रेखा",
    "Standard Meridian of India": "भारत की मानक याम्योत्तर",
    "New Delhi": "नई दिल्ली",
    "Mumbai": "मुंबई",
    "Kolkata": "कोलकाता",
    "Chennai": "चेन्नई",
    # ── Indian Economy ──
    "Gross Domestic Product": "सकल घरेलू उत्पाद",
    "GDP": "जीडीपी",
    "National income": "राष्ट्रीय आय",
    "Inflation": "मुद्रास्फीति",
    "Repo rate": "रेपो दर",
    "Reserve Bank of India": "भारतीय रिज़र्व बैंक",
    "Five Year Plan": "पंचवर्षीय योजना",
    "Budget": "बजट",
    "Direct tax": "प्रत्यक्ष कर",
    "Indirect tax": "अप्रत्यक्ष कर",
    "Goods and Services Tax": "वस्तु एवं सेवा कर",
    "GST": "जीएसटी",
    "Foreign Direct Investment": "प्रत्यक्ष विदेशी निवेश",
    "FDI": "एफडीआई",
    "Import": "आयात",
    "Export": "निर्यात",
    "Balance of Trade": "व्यापार संतुलन",
    "Stock Exchange": "शेयर बाज़ार",
    "Sensex": "सेंसेक्स",
    "SEBI": "सेबी",
    "Poverty line": "गरीबी रेखा",
    "Unemployment": "बेरोजगारी",
    "Green Revolution": "हरित क्रांति",
    # ── Science & Tech (CUET GK) ──
    "space mission": "अंतरिक्ष मिशन",
    "Chandrayaan": "चंद्रयान",
    "ISRO": "इसरो",
    "nuclear power": "परमाणु ऊर्जा",
    "satellite": "उपग्रह",
    "missile": "प्रक्षेपास्त्र",
    "Internet": "इंटरनेट",
    "Artificial Intelligence": "कृत्रिम बुद्धिमत्ता",
    # ── English Grammar ──
    "synonym of": "का पर्यायवाची",
    "antonym of": "का विलोम",
    "meaning of": "का अर्थ",
    "one word substitution": "एक शब्द प्रतिस्थापन",
    "idiom": "मुहावरा",
    "proverb": "कहावत",
    "passive voice": "कर्मवाच्य",
    "active voice": "कर्तृवाच्य",
    "direct speech": "प्रत्यक्ष कथन",
    "indirect speech": "अप्रत्यक्ष कथन",
    "reported speech": "परोक्ष कथन",
    "tense": "काल",
    "preposition": "पूर्वसर्ग",
    "conjunction": "संयोजक",
    "adjective": "विशेषण",
    "adverb": "क्रियाविशेषण",
    "noun": "संज्ञा",
    "pronoun": "सर्वनाम",
    "verb": "क्रिया",
    "sentence": "वाक्य",
    "paragraph": "अनुच्छेद",
    "comprehension": "बोध-परीक्षण",
    "fill in the blank": "रिक्त स्थान भरिए",
    "correct the sentence": "वाक्य सुधारिए",
    "grammatically correct": "व्याकरणिक रूप से सही",
    "spelling": "वर्तनी",
    "vocabulary": "शब्द भंडार",
    # ── Reasoning ──
    "number series": "संख्या श्रृंखला",
    "letter series": "अक्षर श्रृंखला",
    "analogy": "सादृश्य",
    "coding decoding": "कोडिंग-डिकोडिंग",
    "blood relation": "रक्त संबंध",
    "direction sense": "दिशा-ज्ञान",
    "seating arrangement": "बैठक व्यवस्था",
    "syllogism": "न्याय-वाक्य",
    "odd one out": "बेमेल ज्ञात कीजिए",
    "missing number": "लुप्त संख्या",
    "logical sequence": "तार्किक अनुक्रम",
    "calendar": "कैलेंडर",
    "clocks": "घड़ी",
    "puzzle": "पहेली",
    "matrix": "आव्यूह",
    "is related to": "का संबंध है",
    "is to": "का संबंध",
    "comes next": "अगला आता है",
    "find the missing": "लुप्त ज्ञात कीजिए",
    "complete the series": "श्रृंखला पूरी कीजिए",
    "North": "उत्तर", "South": "दक्षिण", "East": "पूर्व", "West": "पश्चिम",
    "Northeast": "उत्तर-पूर्व", "Northwest": "उत्तर-पश्चिम",
    "Southeast": "दक्षिण-पूर्व", "Southwest": "दक्षिण-पश्चिम",
    "father": "पिता", "mother": "माता", "brother": "भाई", "sister": "बहन",
    "son": "पुत्र", "daughter": "पुत्री", "husband": "पति", "wife": "पत्नी",
    "grandfather": "दादा", "grandmother": "दादी", "uncle": "चाचा", "aunt": "चाची",
    # ── Quantitative Aptitude ──
    "percentage": "प्रतिशत",
    "profit and loss": "लाभ और हानि",
    "simple interest": "साधारण ब्याज",
    "compound interest": "चक्रवृद्धि ब्याज",
    "ratio and proportion": "अनुपात और समानुपात",
    "time and work": "समय और कार्य",
    "time speed distance": "समय, चाल और दूरी",
    "speed and distance": "चाल और दूरी",
    "average": "औसत",
    "median": "माध्यिका",
    "mode": "बहुलक",
    "mean": "माध्य",
    "probability": "प्रायिकता",
    "permutation": "क्रमचय",
    "combination": "संचय",
    "area of": "का क्षेत्रफल",
    "perimeter of": "का परिमाप",
    "volume of": "का आयतन",
    "surface area": "पृष्ठ क्षेत्रफल",
    "triangle": "त्रिभुज",
    "circle": "वृत्त",
    "rectangle": "आयत",
    "square": "वर्ग",
    "cylinder": "बेलन",
    "sphere": "गोला",
    "cube": "घन",
    "LCM": "लघुत्तम समापवर्त्य",
    "HCF": "महत्तम समापवर्तक",
    "prime number": "अभाज्य संख्या",
    "even number": "सम संख्या",
    "odd number": "विषम संख्या",
    "fraction": "भिन्न",
    "decimal": "दशमलव",
    "integer": "पूर्णांक",
    "profit": "लाभ",
    "loss": "हानि",
    "discount": "छूट",
    "marked price": "अंकित मूल्य",
    "selling price": "विक्रय मूल्य",
    "cost price": "क्रय मूल्य",
    "principal": "मूलधन",
    "interest": "ब्याज",
    "rate": "दर",
    "time": "समय",
    "distance": "दूरी",
    "speed": "चाल",
    "upstream": "धारा के विरुद्ध",
    "downstream": "धारा के अनुकूल",
    "train": "ट्रेन",
    "pipe": "पाइप",
    "cistern": "हौज",
    "tank": "टंकी",
    "work": "कार्य",
    "worker": "मजदूर",
    "days": "दिन",
    "hours": "घंटे",
    "minutes": "मिनट",
    "years": "वर्ष",
    "months": "महीने",
    "total": "कुल",
    "sum": "योग",
    "difference": "अंतर",
    "product": "गुणनफल",
    "quotient": "भागफल",
    "remainder": "शेषफल",
    # ── Common answer options ──
    "1947": "1947",
    "2500 BCE": "2500 ईसा पूर्व",
    "26 January 1950": "26 जनवरी 1950",
    "15 August 1947": "15 अगस्त 1947",
    "New Delhi": "नई दिल्ली",
    "Mumbai": "मुंबई",
    "Rajasthan": "राजस्थान",
    "Goa": "गोवा",
    "Sanskrit": "संस्कृत",
    "Hindi": "हिंदी",
    "English": "अंग्रेजी",
    "Both": "दोनों",
    "Neither": "कोई नहीं",
    "True": "सत्य",
    "False": "असत्य",
    "Cannot be determined": "निर्धारित नहीं किया जा सकता",
    "Data insufficient": "डेटा अपर्याप्त",
    "flourished around": "लगभग फला-फूला",
    "independent India": "स्वतंत्र भारत",
    "medieval India": "मध्यकालीन भारत",
    "ancient India": "प्राचीन भारत",
    "modern India": "आधुनिक भारत",
},

# ════════════════════════════════════════════════════════════
# BENGALI
# ════════════════════════════════════════════════════════════
"bn": {
    "Which of the following is NOT correct": "নিচের কোনটি সঠিক নয়",
    "Which of the following is correct": "নিচের কোনটি সঠিক",
    "Which of the following": "নিচের কোনটি",
    "None of the above": "উপরের কোনোটিই নয়",
    "All of the above": "উপরের সবগুলো",
    "What is": "কী",
    "Who is": "কে",
    "Where is": "কোথায়",
    "When was": "কখন ছিল",
    "How many": "কতগুলো",
    "Which year": "কোন বছর",
    "Find the": "খুঁজে বের করুন",
    "Calculate": "গণনা করুন",
    "Indian Constitution": "ভারতীয় সংবিধান",
    "Fundamental Rights": "মৌলিক অধিকার",
    "President of India": "ভারতের রাষ্ট্রপতি",
    "Prime Minister of India": "ভারতের প্রধানমন্ত্রী",
    "Parliament of India": "ভারতের সংসদ",
    "Lok Sabha": "লোকসভা",
    "Rajya Sabha": "রাজ্যসভা",
    "Supreme Court": "সুপ্রিম কোর্ট",
    "Article": "অনুচ্ছেদ",
    "Amendment": "সংশোধনী",
    "Indus Valley Civilization": "সিন্ধু সভ্যতা",
    "Indian National Congress": "ভারতীয় জাতীয় কংগ্রেস",
    "Quit India Movement": "ভারত ছাড়ো আন্দোলন",
    "Mahatma Gandhi": "মহাত্মা গান্ধী",
    "Jawaharlal Nehru": "জওহরলাল নেহরু",
    "Rabindranath Tagore": "রবীন্দ্রনাথ ঠাকুর",
    "B.R. Ambedkar": "বি.আর. আম্বেদকর",
    "River Ganga": "গঙ্গা নদী",
    "Western Ghats": "পশ্চিমঘাট",
    "New Delhi": "নয়া দিল্লি",
    "Gross Domestic Product": "মোট দেশজ উৎপাদন",
    "GDP": "জিডিপি",
    "Reserve Bank of India": "ভারতীয় রিজার্ভ ব্যাংক",
    "GST": "জিএসটি",
    "Green Revolution": "সবুজ বিপ্লব",
    "ISRO": "ইসরো",
    "percentage": "শতাংশ",
    "profit and loss": "লাভ ও ক্ষতি",
    "simple interest": "সরল সুদ",
    "compound interest": "চক্রবৃদ্ধি সুদ",
    "average": "গড়",
    "probability": "সম্ভাবনা",
    "area of": "এর ক্ষেত্রফল",
    "triangle": "ত্রিভুজ",
    "circle": "বৃত্ত",
    "rectangle": "আয়তক্ষেত্র",
    "number series": "সংখ্যা ধারা",
    "analogy": "সাদৃশ্য",
    "blood relation": "রক্ত সম্পর্ক",
    "direction sense": "দিক জ্ঞান",
    "North": "উত্তর", "South": "দক্ষিণ", "East": "পূর্ব", "West": "পশ্চিম",
    "father": "বাবা", "mother": "মা", "brother": "ভাই", "sister": "বোন",
    "synonym of": "এর প্রতিশব্দ",
    "antonym of": "এর বিপরীত শব্দ",
    "passive voice": "কর্মবাচ্য",
    "active voice": "কর্তৃবাচ্য",
    "profit": "লাভ", "loss": "ক্ষতি", "discount": "ছাড়",
    "speed": "গতি", "distance": "দূরত্ব", "time": "সময়",
    "Both A and B": "A এবং B উভয়ই",
    "Neither A nor B": "A বা B কোনোটিই না",
    "flourished around": "প্রায় সমৃদ্ধ হয়েছিল",
    "2500 BCE": "২৫০০ খ্রিস্টপূর্ব",
    "15 August 1947": "১৫ আগস্ট ১৯৪৭",
    "26 January 1950": "২৬ জানুয়ারি ১৯৫০",
},

# ════════════════════════════════════════════════════════════
# TAMIL
# ════════════════════════════════════════════════════════════
"ta": {
    "Which of the following is NOT correct": "பின்வருவனவற்றில் எது சரியானதல்ல",
    "Which of the following is correct": "பின்வருவனவற்றில் எது சரியானது",
    "Which of the following": "பின்வருவனவற்றில் எது",
    "None of the above": "மேற்கூறியவற்றில் எதுவுமில்லை",
    "All of the above": "மேற்கூறியவை அனைத்தும்",
    "What is": "என்ன",
    "Who is": "யார்",
    "Where is": "எங்கே",
    "When was": "எப்போது",
    "How many": "எத்தனை",
    "Find the": "கண்டறி",
    "Calculate": "கணக்கிடு",
    "Indian Constitution": "இந்திய அரசியலமைப்பு",
    "Fundamental Rights": "அடிப்படை உரிமைகள்",
    "President of India": "இந்தியாவின் ஜனாதிபதி",
    "Prime Minister of India": "இந்தியாவின் பிரதமர்",
    "Parliament of India": "இந்திய நாடாளுமன்றம்",
    "Lok Sabha": "மக்களவை",
    "Rajya Sabha": "மாநிலங்களவை",
    "Supreme Court": "உச்ச நீதிமன்றம்",
    "Article": "பிரிவு",
    "Amendment": "திருத்தம்",
    "Indus Valley Civilization": "சிந்து சமவெளி நாகரீகம்",
    "Indian National Congress": "இந்திய தேசிய காங்கிரஸ்",
    "Quit India Movement": "வெள்ளையனே வெளியேறு இயக்கம்",
    "Mahatma Gandhi": "மகாத்மா காந்தி",
    "Jawaharlal Nehru": "ஜவஹர்லால் நேரு",
    "Rabindranath Tagore": "ரவீந்திரநாத் தாகூர்",
    "B.R. Ambedkar": "பி.ஆர். அம்பேத்கர்",
    "River Ganga": "கங்கை ஆறு",
    "New Delhi": "புது டெல்லி",
    "Gross Domestic Product": "மொத்த உள்நாட்டு உற்பத்தி",
    "GDP": "ஜிடிபி",
    "Reserve Bank of India": "இந்திய ரிசர்வ் வங்கி",
    "GST": "ஜிஎஸ்டி",
    "Green Revolution": "பசுமை புரட்சி",
    "ISRO": "இஸ்ரோ",
    "percentage": "சதவீதம்",
    "profit and loss": "லாபம் மற்றும் நஷ்டம்",
    "simple interest": "தனி வட்டி",
    "compound interest": "கூட்டு வட்டி",
    "average": "சராசரி",
    "probability": "நிகழ்தகவு",
    "triangle": "முக்கோணம்",
    "circle": "வட்டம்",
    "North": "வடக்கு", "South": "தெற்கு", "East": "கிழக்கு", "West": "மேற்கு",
    "father": "தந்தை", "mother": "தாய்", "brother": "சகோதரன்", "sister": "சகோதரி",
    "synonym of": "இன் ஒத்த சொல்",
    "antonym of": "இன் எதிர்ச்சொல்",
    "passive voice": "செயப்பாட்டு வினை",
    "active voice": "செய்வினை",
    "profit": "லாபம்", "loss": "நஷ்டம்", "discount": "தள்ளுபடி",
    "speed": "வேகம்", "distance": "தூரம்", "time": "நேரம்",
    "number series": "எண் தொடர்",
    "analogy": "உவமை",
    "blood relation": "இரத்த உறவு",
    "direction sense": "திசை உணர்வு",
    "Both A and B": "A மற்றும் B இரண்டும்",
    "Neither A nor B": "A அல்லது B இல்லை",
    "flourished around": "சுமார் செழித்தது",
    "2500 BCE": "2500 பொ.ஆ.மு.",
},

# ════════════════════════════════════════════════════════════
# TELUGU
# ════════════════════════════════════════════════════════════
"te": {
    "Which of the following is NOT correct": "కింది వాటిలో ఏది సరికాదు",
    "Which of the following is correct": "కింది వాటిలో ఏది సరైనది",
    "Which of the following": "కింది వాటిలో ఏది",
    "None of the above": "పైన చెప్పినవేవీ కాదు",
    "All of the above": "పైన చెప్పినవన్నీ",
    "What is": "ఏమిటి",
    "Who is": "ఎవరు",
    "Where is": "ఎక్కడ",
    "When was": "ఎప్పుడు",
    "How many": "ఎన్ని",
    "Find the": "కనుగొనండి",
    "Calculate": "లెక్కించండి",
    "Indian Constitution": "భారత రాజ్యాంగం",
    "Fundamental Rights": "ప్రాథమిక హక్కులు",
    "President of India": "భారత రాష్ట్రపతి",
    "Prime Minister of India": "భారత ప్రధానమంత్రి",
    "Parliament of India": "భారత పార్లమెంటు",
    "Lok Sabha": "లోక్ సభ",
    "Rajya Sabha": "రాజ్య సభ",
    "Supreme Court": "సుప్రీంకోర్టు",
    "Article": "అధికరణ",
    "Amendment": "సవరణ",
    "Indus Valley Civilization": "సింధు లోయ నాగరికత",
    "Indian National Congress": "భారత జాతీయ కాంగ్రెస్",
    "Quit India Movement": "క్విట్ ఇండియా ఉద్యమం",
    "Mahatma Gandhi": "మహాత్మా గాంధీ",
    "Jawaharlal Nehru": "జవహర్‌లాల్ నెహ్రూ",
    "B.R. Ambedkar": "బి.ఆర్. అంబేద్కర్",
    "River Ganga": "గంగా నది",
    "New Delhi": "న్యూఢిల్లీ",
    "GDP": "జిడిపి",
    "GST": "జిఎస్టి",
    "Reserve Bank of India": "భారతీయ రిజర్వ్ బ్యాంక్",
    "Green Revolution": "హరిత విప్లవం",
    "ISRO": "ఇస్రో",
    "percentage": "శాతం",
    "profit and loss": "లాభనష్టాలు",
    "simple interest": "సాధారణ వడ్డీ",
    "compound interest": "చక్రవడ్డీ",
    "average": "సగటు",
    "probability": "సంభావ్యత",
    "triangle": "త్రిభుజం",
    "circle": "వృత్తం",
    "North": "ఉత్తరం", "South": "దక్షిణం", "East": "తూర్పు", "West": "పడమర",
    "father": "తండ్రి", "mother": "తల్లి", "brother": "అన్న/తమ్ముడు", "sister": "అక్క/చెల్లి",
    "profit": "లాభం", "loss": "నష్టం", "discount": "తగ్గింపు",
    "speed": "వేగం", "distance": "దూరం", "time": "సమయం",
    "synonym of": "యొక్క పర్యాయపదం",
    "antonym of": "యొక్క విరుద్ధ పదం",
    "number series": "సంఖ్యల శ్రేణి",
    "blood relation": "రక్త సంబంధం",
    "direction sense": "దిక్కుల జ్ఞానం",
    "Both A and B": "A మరియు B రెండూ",
    "Neither A nor B": "A కాదు B కాదు",
    "flourished around": "సుమారుగా వర్ధిల్లింది",
},

# ════════════════════════════════════════════════════════════
# GUJARATI
# ════════════════════════════════════════════════════════════
"gu": {
    "Which of the following is NOT correct": "નીચેનામાંથી કયું સાચું નથી",
    "Which of the following is correct": "નીચેનામાંથી કયું સાચું છે",
    "Which of the following": "નીચેનામાંથી કયું",
    "None of the above": "ઉપરોક્ત પૈકી કોઈ નહીં",
    "All of the above": "ઉપરોક્ત તમામ",
    "What is": "શું છે",
    "Who is": "કોણ છે",
    "Where is": "ક્યાં છે",
    "When was": "ક્યારે હતું",
    "How many": "કેટલા",
    "Find the": "શોધો",
    "Calculate": "ગણો",
    "Indian Constitution": "ભારતીય બંધારણ",
    "Fundamental Rights": "મૂળભૂત અધિકારો",
    "President of India": "ભારતના રાષ્ટ્રપ્રમુખ",
    "Prime Minister of India": "ભારતના વડાપ્રધાન",
    "Parliament of India": "ભારતની સંસદ",
    "Lok Sabha": "લોકસભા",
    "Rajya Sabha": "રાજ્યસભા",
    "Supreme Court": "સર્વોચ્ચ ન્યાયાલય",
    "Article": "અનુચ્છેદ",
    "Amendment": "સુધારો",
    "Indus Valley Civilization": "સિંધુ ખીણ સભ્યતા",
    "Indian National Congress": "ભારતીય રાષ્ટ્રીય કોંગ્રેસ",
    "Quit India Movement": "ભારત છોડો ચળવળ",
    "Mahatma Gandhi": "મહાત્મા ગાંધી",
    "Jawaharlal Nehru": "જવાહરલાલ નહેરુ",
    "B.R. Ambedkar": "બી.આર. આંબેડકર",
    "Sardar Vallabhbhai Patel": "સરદાર વલ્લભભાઈ પટેલ",
    "River Ganga": "ગંગા નદી",
    "New Delhi": "નવી દિલ્હી",
    "GDP": "જીડીપી",
    "GST": "જીએસટી",
    "Reserve Bank of India": "ભારતીય રિઝર્વ બેન્ક",
    "Green Revolution": "હરિત ક્રાંતિ",
    "ISRO": "ઇસરો",
    "percentage": "ટકાવારી",
    "profit and loss": "નફો અને નુકસાન",
    "simple interest": "સાદું વ્યાજ",
    "compound interest": "ચક્રવૃદ્ધિ વ્યાજ",
    "average": "સરેરાશ",
    "probability": "સંભાવના",
    "triangle": "ત્રિકોણ",
    "circle": "વર્તુળ",
    "North": "ઉત્તર", "South": "દક્ષિણ", "East": "પૂર્વ", "West": "પશ્ચિમ",
    "father": "પિતા", "mother": "માતા", "brother": "ભાઈ", "sister": "બહેન",
    "profit": "નફો", "loss": "નુકસાન", "discount": "છૂટ",
    "speed": "ઝડપ", "distance": "અંતર", "time": "સમય",
    "synonym of": "નો સમાનાર્થી",
    "antonym of": "નો વિરોધાભાસ",
    "number series": "સંખ્યા ક્રમ",
    "blood relation": "રક્ત સંબંધ",
    "direction sense": "દિશા જ્ઞાન",
    "Both A and B": "A અને B બંને",
    "Neither A nor B": "A કે B નહીં",
    "flourished around": "આશરે વિકસ્યું",
    "2500 BCE": "2500 ઈ.પૂ.",
},

# ════════════════════════════════════════════════════════════
# MARATHI
# ════════════════════════════════════════════════════════════
"mr": {
    "Which of the following is NOT correct": "खालीलपैकी कोणते बरोबर नाही",
    "Which of the following is correct": "खालीलपैकी कोणते बरोबर आहे",
    "Which of the following": "खालीलपैकी कोणते",
    "None of the above": "वरीलपैकी कोणतेही नाही",
    "All of the above": "वरील सर्व",
    "What is": "काय आहे",
    "Who is": "कोण आहे",
    "Where is": "कुठे आहे",
    "When was": "केव्हा होते",
    "How many": "किती",
    "Find the": "शोधा",
    "Calculate": "गणना करा",
    "Indian Constitution": "भारतीय राज्यघटना",
    "Fundamental Rights": "मूलभूत हक्क",
    "President of India": "भारताचे राष्ट्रपती",
    "Prime Minister of India": "भारताचे पंतप्रधान",
    "Parliament of India": "भारताची संसद",
    "Lok Sabha": "लोकसभा",
    "Rajya Sabha": "राज्यसभा",
    "Supreme Court": "सर्वोच्च न्यायालय",
    "Article": "कलम",
    "Amendment": "दुरुस्ती",
    "Indus Valley Civilization": "सिंधू संस्कृती",
    "Indian National Congress": "भारतीय राष्ट्रीय काँग्रेस",
    "Quit India Movement": "चले जाव आंदोलन",
    "Mahatma Gandhi": "महात्मा गांधी",
    "Jawaharlal Nehru": "जवाहरलाल नेहरू",
    "B.R. Ambedkar": "बी.आर. आंबेडकर",
    "Sardar Vallabhbhai Patel": "सरदार वल्लभभाई पटेल",
    "River Ganga": "गंगा नदी",
    "New Delhi": "नवी दिल्ली",
    "GDP": "जीडीपी",
    "GST": "जीएसटी",
    "Reserve Bank of India": "भारतीय रिझर्व्ह बँक",
    "Green Revolution": "हरित क्रांती",
    "ISRO": "इस्रो",
    "percentage": "टक्केवारी",
    "profit and loss": "नफा आणि तोटा",
    "simple interest": "साधे व्याज",
    "compound interest": "चक्रवाढ व्याज",
    "average": "सरासरी",
    "probability": "संभाव्यता",
    "triangle": "त्रिकोण",
    "circle": "वर्तुळ",
    "North": "उत्तर", "South": "दक्षिण", "East": "पूर्व", "West": "पश्चिम",
    "father": "वडील", "mother": "आई", "brother": "भाऊ", "sister": "बहीण",
    "profit": "नफा", "loss": "तोटा", "discount": "सवलत",
    "speed": "वेग", "distance": "अंतर", "time": "वेळ",
    "synonym of": "चा समानार्थी शब्द",
    "antonym of": "चा विरुद्धार्थी शब्द",
    "number series": "संख्या मालिका",
    "blood relation": "रक्त संबंध",
    "direction sense": "दिशा ज्ञान",
    "Both A and B": "A आणि B दोन्ही",
    "Neither A nor B": "A किंवा B कोणतेही नाही",
    "flourished around": "सुमारे भरभराट झाली",
    "2500 BCE": "2500 ईसापूर्व",
},

# ════════════════════════════════════════════════════════════
# KANNADA
# ════════════════════════════════════════════════════════════
"kn": {
    "Which of the following is NOT correct": "ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಯಾವುದು ಸರಿಯಲ್ಲ",
    "Which of the following is correct": "ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಯಾವುದು ಸರಿಯಾಗಿದೆ",
    "Which of the following": "ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಯಾವುದು",
    "None of the above": "ಮೇಲಿನ ಯಾವುದೂ ಇಲ್ಲ",
    "All of the above": "ಮೇಲಿನ ಎಲ್ಲವೂ",
    "What is": "ಏನು",
    "Who is": "ಯಾರು",
    "Where is": "ಎಲ್ಲಿ",
    "When was": "ಯಾವಾಗ",
    "How many": "ಎಷ್ಟು",
    "Find the": "ಕಂಡುಹಿಡಿಯಿರಿ",
    "Calculate": "ಲೆಕ್ಕ ಹಾಕಿ",
    "Indian Constitution": "ಭಾರತೀಯ ಸಂವಿಧಾನ",
    "Fundamental Rights": "ಮೂಲಭೂತ ಹಕ್ಕುಗಳು",
    "President of India": "ಭಾರತದ ರಾಷ್ಟ್ರಪತಿ",
    "Prime Minister of India": "ಭಾರತದ ಪ್ರಧಾನಮಂತ್ರಿ",
    "Parliament of India": "ಭಾರತದ ಸಂಸತ್ತು",
    "Lok Sabha": "ಲೋಕಸಭೆ",
    "Rajya Sabha": "ರಾಜ್ಯಸಭೆ",
    "Supreme Court": "ಸರ್ವೋಚ್ಚ ನ್ಯಾಯಾಲಯ",
    "Article": "ವಿಧಿ",
    "Amendment": "ತಿದ್ದುಪಡಿ",
    "Indus Valley Civilization": "ಸಿಂಧೂ ಕಣಿವೆ ನಾಗರಿಕತೆ",
    "Indian National Congress": "ಭಾರತೀಯ ರಾಷ್ಟ್ರೀಯ ಕಾಂಗ್ರೆಸ್",
    "Quit India Movement": "ಭಾರತ ಬಿಟ್ಟು ತೊಲಗಿ ಚಳವಳಿ",
    "Mahatma Gandhi": "ಮಹಾತ್ಮ ಗಾಂಧಿ",
    "Jawaharlal Nehru": "ಜವಾಹರಲಾಲ್ ನೆಹರು",
    "B.R. Ambedkar": "ಬಿ.ಆರ್. ಅಂಬೇಡ್ಕರ್",
    "River Ganga": "ಗಂಗಾ ನದಿ",
    "New Delhi": "ನವದೆಹಲಿ",
    "GDP": "ಜಿಡಿಪಿ",
    "GST": "ಜಿಎಸ್ಟಿ",
    "Reserve Bank of India": "ಭಾರತೀಯ ರಿಸರ್ವ್ ಬ್ಯಾಂಕ್",
    "Green Revolution": "ಹಸಿರು ಕ್ರಾಂತಿ",
    "ISRO": "ಇಸ್ರೋ",
    "percentage": "ಶೇಕಡಾ",
    "profit and loss": "ಲಾಭ ಮತ್ತು ನಷ್ಟ",
    "simple interest": "ಸರಳ ಬಡ್ಡಿ",
    "compound interest": "ಚಕ್ರಬಡ್ಡಿ",
    "average": "ಸರಾಸರಿ",
    "probability": "ಸಂಭಾವ್ಯತೆ",
    "triangle": "ತ್ರಿಭುಜ",
    "circle": "ವೃತ್ತ",
    "North": "ಉತ್ತರ", "South": "ದಕ್ಷಿಣ", "East": "ಪೂರ್ವ", "West": "ಪಶ್ಚಿಮ",
    "father": "ತಂದೆ", "mother": "ತಾಯಿ", "brother": "ಅಣ್ಣ/ತಮ್ಮ", "sister": "ಅಕ್ಕ/ತಂಗಿ",
    "profit": "ಲಾಭ", "loss": "ನಷ್ಟ", "discount": "ರಿಯಾಯಿತಿ",
    "speed": "ವೇಗ", "distance": "ದೂರ", "time": "ಸಮಯ",
    "synonym of": "ಯ ಸಮಾನಾರ್ಥಕ",
    "antonym of": "ಯ ವಿರುದ್ಧಾರ್ಥಕ",
    "number series": "ಸಂಖ್ಯಾ ಸರಣಿ",
    "blood relation": "ರಕ್ತ ಸಂಬಂಧ",
    "direction sense": "ದಿಕ್ಕಿನ ಅರಿವು",
    "Both A and B": "A ಮತ್ತು B ಎರಡೂ",
    "Neither A nor B": "A ಅಲ್ಲ B ಅಲ್ಲ",
    "flourished around": "ಸುಮಾರು ಅಭಿವೃದ್ಧಿ ಹೊಂದಿತು",
},

# ════════════════════════════════════════════════════════════
# ODIA
# ════════════════════════════════════════════════════════════
"or": {
    "Which of the following is NOT correct": "ନିମ୍ନଲିଖିତ ମଧ୍ୟରୁ କେଉଁଟି ସଠିକ ନୁହଁ",
    "Which of the following is correct": "ନିମ୍ନଲିଖିତ ମଧ୍ୟରୁ କେଉଁଟି ସଠିକ",
    "Which of the following": "ନିମ୍ନଲିଖିତ ମଧ୍ୟରୁ କେଉଁଟି",
    "None of the above": "ଉପରୋକ୍ତ କୋଣଟି ନୁହଁ",
    "All of the above": "ଉପରୋକ୍ତ ସମସ୍ତ",
    "What is": "କ'ଣ",
    "Who is": "କିଏ",
    "Where is": "କେଉଁଠାରେ",
    "When was": "କେବେ ଥିଲା",
    "How many": "କେତୋଟି",
    "Find the": "ଖୋଜ",
    "Calculate": "ଗଣନା କର",
    "Indian Constitution": "ଭାରତୀୟ ସମ୍ବିଧାନ",
    "Fundamental Rights": "ମୌଳିକ ଅଧିକାର",
    "President of India": "ଭାରତର ରାଷ୍ଟ୍ରପତି",
    "Prime Minister of India": "ଭାରତର ପ୍ରଧାନମନ୍ତ୍ରୀ",
    "Parliament of India": "ଭାରତୀୟ ସଂସଦ",
    "Lok Sabha": "ଲୋକ ସଭା",
    "Rajya Sabha": "ରାଜ୍ୟ ସଭା",
    "Supreme Court": "ସର୍ବୋଚ୍ଚ ନ୍ୟାୟାଳୟ",
    "Article": "ଅନୁଚ୍ଛେଦ",
    "Amendment": "ସଂଶୋଧନ",
    "Indus Valley Civilization": "ସିନ୍ଧୁ ଉପତ୍ୟକା ସଭ୍ୟତା",
    "Indian National Congress": "ଭାରତୀୟ ଜାତୀୟ କଂଗ୍ରେସ",
    "Quit India Movement": "ଭାରତ ଛାଡ ଆନ୍ଦୋଳନ",
    "Mahatma Gandhi": "ମହାତ୍ମା ଗାନ୍ଧୀ",
    "Jawaharlal Nehru": "ଜୱାହରଲାଲ ନେହରୁ",
    "B.R. Ambedkar": "ବି.ଆର. ଆମ୍ବେଡ୍କର",
    "River Ganga": "ଗଙ୍ଗା ନଦୀ",
    "New Delhi": "ନୂଆ ଦିଲ୍ଲୀ",
    "GDP": "ଜିଡିପି",
    "GST": "ଜିଏସଟି",
    "Reserve Bank of India": "ଭାରତୀୟ ରିଜର୍ଭ ବ୍ୟାଙ୍କ",
    "Green Revolution": "ସବୁଜ ବିପ୍ଳବ",
    "ISRO": "ଇସ୍ରୋ",
    "percentage": "ଶତାଂଶ",
    "profit and loss": "ଲାଭ ଓ ହାନି",
    "simple interest": "ସରଳ ସୁଧ",
    "compound interest": "ଚକ୍ରବୃଦ୍ଧି ସୁଧ",
    "average": "ହାରାହାରି",
    "probability": "ସମ୍ଭାବ୍ୟତା",
    "triangle": "ତ୍ରିଭୁଜ",
    "circle": "ବୃତ୍ତ",
    "North": "ଉତ୍ତର", "South": "ଦକ୍ଷିଣ", "East": "ପୂର୍ବ", "West": "ପଶ୍ଚିମ",
    "father": "ପିତା", "mother": "ମାତା", "brother": "ଭାଇ", "sister": "ଭଉଣୀ",
    "profit": "ଲାଭ", "loss": "ହାନି", "discount": "ରିହାତି",
    "speed": "ବେଗ", "distance": "ଦୂରତ୍ବ", "time": "ସମୟ",
    "synonym of": "ର ସମାର୍ଥ ଶବ୍ଦ",
    "antonym of": "ର ବିରୋଧ ଶବ୍ଦ",
    "number series": "ସଂଖ୍ୟା ଧାଡ଼ି",
    "blood relation": "ରକ୍ତ ସମ୍ପର୍କ",
    "direction sense": "ଦିଗ ଜ୍ଞାନ",
    "Both A and B": "A ଏବଂ B ଉଭୟ",
    "Neither A nor B": "A ବି ନୁହଁ B ବି ନୁହଁ",
    "flourished around": "ପ୍ରାୟ ସମୃଦ୍ଧ ହୋଇଥିଲା",
},
}

def build_replacer(phrases: dict):
    """Longest-phrase-first replacer for accurate translation."""
    sorted_phrases = sorted(phrases.items(), key=lambda x: -len(x[0]))
    def replace(text: str) -> str:
        if not text or not isinstance(text, str): return text
        for eng, native in sorted_phrases:
            if eng.lower() in text.lower():
                # Case-insensitive replacement
                pattern = re.compile(re.escape(eng), re.IGNORECASE)
                text = pattern.sub(native, text)
        return text
    return replace

def translate_cuet_all_languages():
    conn = _bank_conn()
    CUET_SUBJECTS = ['CUET_GK', 'CUET_English', 'CUET_Reasoning', 'CUET_Quantitative']
    LANGS = ['hi', 'bn', 'ta', 'te', 'gu', 'mr', 'kn', 'or']
    COLS = ['question', 'option_a', 'option_b', 'option_c', 'option_d']

    for lang in LANGS:
        replacer = build_replacer(CUET_PHRASES.get(lang, {}))
        print(f"\n🔄 Re-translating CUET → {lang}...")
        for subj in CUET_SUBJECTS:
            # Get all rows for this subject
            rows = conn.execute(
                f'SELECT qb_id, question_en, option_a_en, option_b_en, option_c_en, option_d_en '
                f'FROM question_bank WHERE subject=?', (subj,)
            ).fetchall()

            updates = []
            for row in rows:
                qb_id = row[0]
                translated = [replacer(str(row[i+1])) if row[i+1] else '' for i in range(5)]
                updates.append((*translated, qb_id))

            with _bank_lock:
                conn.executemany(
                    f'''UPDATE question_bank SET
                        question_{lang}=?, option_a_{lang}=?, option_b_{lang}=?,
                        option_c_{lang}=?, option_d_{lang}=?
                        WHERE qb_id=?''',
                    updates
                )
            conn.commit()
            print(f"  ✅ {subj}: {len(rows):,} rows updated")

    # Final check
    print("\n📊 Translation coverage after fix:")
    for lang in LANGS:
        for subj in CUET_SUBJECTS:
            total = conn.execute('SELECT COUNT(*) FROM question_bank WHERE subject=?', (subj,)).fetchone()[0]
            same = conn.execute(
                f'SELECT COUNT(*) FROM question_bank WHERE subject=? AND question_{lang}=question_en',
                (subj,)
            ).fetchone()[0]
            pct_translated = round((total - same) / total * 100, 1) if total > 0 else 0
            print(f"  {subj} [{lang}]: {pct_translated}% actually translated ({total-same}/{total})")

if __name__ == '__main__':
    print("🌐 CUET Translation Fix — Applying comprehensive Indian GK dictionary...")
    t0 = time.time()
    translate_cuet_all_languages()
    print(f"\n✅ Done in {time.time()-t0:.1f}s")
